language: node_js
node_js:
    - 12.14.1
cache:  npm 
sudo:
    false

install:
    - npm ci
    - npm install typescript -g
    - npm install codecov -g   
scripts: 
    - tsc
    - nyc npm test 
    - npm run coverage
    - codecov 

notifications:
    email: 
      recipients:
        - info@fake-mm.ru
    on_success: never
    on_failure: always