language: node_js
node_js:
    - 12.14.1
cache:  npm 
 

install:
    - npm ci
   # - npm install codecov -g 
scripts: 
    - npm test 
   # - codecov

notifications:
    email: 
      recipients:
        - info@fake-mm.ru
    on_success: never
    on_failure: always