language: node_js

install:
    - npm install codecov -g
    - npm install ntsc -g 
    - npm i
scripts: 
    - istanbul cover ./node_modules/mocha/bin/_mocha --reporter lcovonly -- -R spec
    - codecov
    - ntsc
    - npm test 

notifications:
    email: 
      recipients:
        - info@fake-mm.ru
    on_success: never
    on_failure: always